try {
    console.log(number);
}
catch(error){
console.log(error +" has been catch")
}